### ISSUE TITLE
Token work for both models

### ISSUE THREAD

**Issue by bayucakra20** [sfelix-martins/passport-multiauth#11]
Hello sfelix,

Thanks for making this amazing package, I have followed your usage about how implemented this package, and its work fine, after I realize, token that I generate for models `User` can use for models `Admin` too

On the last issue, you said to add header request `Accept: application/json;`. Than I add it, but I've still got the same problem.

Any idea to fix this?

Thanks

**Comment by sfelix-martins** [comment]
Thanks @bayucakra20. This is the same problem on #5 . Make sure that you are on branch `master`. I am preparing a new release. But you can use the branch master to solve your problem for a while. Within your `composer.json` project file set:

```json
"minimum-stability": "dev",
"prefer-stable": true,
"require": {
  "smartins/passport-multiauth": "dev-master"
}
```

And update the package:

```sh
composer update smartins/passport-multiauth
```

I hope it helps.

**Comment by sfelix-martins** [comment]
The release [v1.0.0](https://github.com/sfelix-martins/passport-multiauth/releases/tag/v1.0.0) fix the problem with access tokens working with many models with same database id. Please, update to this version. ;)

**Comment by bayucakra20** [comment]
I remove `api` middleware from routes, now it worked :+1: 

Thanks @sfelix-martins for your latest release update.

Finally I can implement multi auth using laravel passport :D

But, I want to ask, while I attempt to authenticate user admins, I got `Method attempt does not exist`, Is it possible to use `Auth::attempt` method?

**Comment by sfelix-martins** [comment]
Thanks @bayucakra20. I think that `Auth::attempt()` method only works to authenticate using `session` driver.

When I needed check if user can to be authenticated I use the following code:

```php

use Illuminate\Contracts\Hashing\Hasher;
use Illuminate\Foundation\Auth\User as Authenticatable;

class AuthenticateExample
{
    protected $model;

    protected $hasher;

    public function __construct(Authenticatable $model, Hasher $hasher)
    {
        $this->model = $model;
        $this->hasher = $hasher;
    }

    public function getEntityByCredentials($username, $password)
    {
        if (method_exists($this->model, 'findForPassport')) {
            $user = (new $this->model)->findForPassport($username);
        } else {
            $user = (new $this->model)->where('email', $username)->first();
        }

        if (! $user) {
            return;
        } elseif (method_exists($user, 'validateForPassportPasswordGrant')) {
            if (! $user->validateForPassportPasswordGrant($password)) {
                return;
            }
        } elseif (! $this->hasher->check($password, $user->getAuthPassword())) {
            return;
        }

        return $user;
    }
}
```

And create a [personal access token](https://laravel.com/docs/master/passport#creating-a-personal-access-client) using `createToken()` method from `HasApiTokens`:

```php
      $entity = $this->authExample->getEntityByCredentials($username, $password);

      if (! $entity) {
          throw OAuthServerException::invalidCredentials();
      }

      $accessToken = $entity->createToken($name);
```

I hope it helps. ;)

**Comment by ErwanTouba** [comment]
I know this should have been resolved but unfortunatly not in my case.

i use the master version of the package, along with laravel 5.5 and passport 4.0
"smartins/passport-multiauth": "dev-master"

i have a route, which return an instance of the authenticated model.
i'm authenticated with the 'api "User" access_token

Route::middleware('auth:api,professional')->get('/user', function (Request $request) {
  var_dump(Auth::guard('api')->user()); // this retrieve "User" model with id=6
  var_dump(Auth::guard('professional')->user()); // // this retrieve "Professional" model with id=6

 return response()->json('ok');
});

any idea why its having this behaviour ?

**Comment by sfelix-martins** [comment]
@ErwanTouba This issue was solved on version 1.0. The code on branch `master` has a pre-release to version 2.0 and don't have compatibility with this older version (1.0). Please, check if your project was configured correctly:

# Upgrade Guide

## Upgrading to 2.0 from 1.0

### Updating Dependencies

Update the `smartins/passport-multiauth` dependency to `^2.0` in your `composer.json` file.

**OBS:** If you have problems using `laravel/passport` `2.0.*` please update to >= `3.0`.

### Update configs

On `app/Http/Kernel.php` remove the `SMartins\PassportMultiauth\Http\Middleware\ConfigAccessTokenCustomProvider` from your middlewares.
Now you need just of `SMartins\PassportMultiauth\Http\Middleware\AddCustomProvider::class` to use in your `forAccessTokens` `Laravel/Passport` routes. Replace the default `auth` middleware from `Illuminate\Auth\Middleware\Authenticate::class` to `SMartins\PassportMultiauth\Http\Middleware\MultiAuthenticate::class`:

```php
class Kernel extends HttpKernel
{
    // ...

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        // ** Replace auth middleware **
        // 'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth' => \SMartins\PassportMultiauth\Http\Middleware\MultiAuthenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        // Keep the `AddCustomProvider`
        'oauth.providers' => \SMartins\PassportMultiauth\Http\Middleware\AddCustomProvider::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];

    // ...
}
```

* Change the middleware on `Laravel\Passport` routes on `AuthServiceProvider`:

```php

namespace App\Providers;

use Route;
use Laravel\Passport\Passport;
use Illuminate\Support\Facades\Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    // ...

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        Passport::routes();

        // Middleware `oauth.providers` middleware defined on $routeMiddleware above
        Route::group(['middleware' => 'oauth.providers'], function () {
            Passport::routes(function ($router) {
                return $router->forAccessTokens();
            });
        });
    }
    // ...
}
```

### Request and Auth

On `v2.0` you don't need to pass the guard `api` to routes that has multi-auth guard. E.g.:

* On `v1.0` to use more than one guard on `auth` middleware you should do something like:

```php
Route::middleware('auth:admin,api')->get('users', function (Request $request) {
    return $request->user('api'); // Return an instance of `Admin` or `User`
});

// Or to just one guard with not default middleware (api):
Route::middleware('auth:admin')->get('admin', function (Request $request) {
    return $request->user('admin');
});
```

* On `v2.0` in all cases you can use `$request->user()`, without the guard. E.g.:

```php
Route::middleware('auth:admin,api')->get('users', function (Request $request) {
    return $request->user(); // Returns an instance of `Admin` or `User`
});

// Or to just one guard with not default middleware (api):
Route::middleware('auth:admin')->get('admin', function (Request $request) {
    return $request->user(); // Returns an instance of `Admin` 
});

Route::middleware('auth:admin,api,customer')->get('users', function (Request $request) {
    // You can specify the guard
    return $request->user('customer'); // Returns an instance of `Customer` or `null`
});
```

* You can use too the `Auth` facade:

```php
Auth::check();
Auth::user();
```

### Scopes

On older major release (v1.0), to use scopes you should replace the `Laravel\Passport` scopes middlewares to package middlewares:

```php
// On version 1.0.
    'multiauth.scope' => \SMartins\PassportMultiauth\Http\Middleware\MultiAuthCheckForAnyScope::class,
    'multiauth.scopes' => \SMartins\PassportMultiauth\Http\Middleware\MultiAuthCheckScopes::class,
```

On version 2.0 you must do the opposite way. Just uses the default middlewares from `Larave\Passport`:

```php
// On version 2.0.
    'scopes' => \Laravel\Passport\Http\Middleware\CheckScopes::class,
    'scope' => \Laravel\Passport\Http\Middleware\CheckForAnyScope::class,
```

Read more about laravel passport scopes on [official docs](https://laravel.com/docs/5.5/passport#checking-scopes)

### Unit tests

Instead to use the `Laravel\Passport\Passport::actingAs()` method, use `SMartins\PassportMultiauth\PassportMultiauth::actingAs()`.
The difference is that the `actingAs` from this package get the guard based on `Authenticatable` instance passed on first parameter and authenticate this user using your guard. E.g.:

```php
use App\User;
use Tests\TestCase;
use SMartins\PassportMultiauth\PassportMultiauth;

class AuthTest extends TestCase
{
    public function fooTest()
    {
        $user = factory(User::class)->create();

        PassportMultiauth::actingAs($user);

        $this->json('GET', 'api/user');
    }
}
```

**Comment by sfelix-martins** [comment]
@ErwanTouba  If the problem still exists please reopen the issue

**Comment by mdmusaib** [comment]
Hi! sfelix martins, I'm a beginner in laravel, trying to implement multiple auth using passport api, first thing first is i have cloned your repository and done with the basic command which you specified in github readme file, What i want to know is how do i create a user, admin and generate particular access_token for them, i don't have an idea of this, could you please explain me very detailed!!!plss

**Comment by sfelix-martins** [comment]
@mdmusaib Please, create a specific issue to your problem. This issue is closed. Another issue will help another people with the same problem found the solution more easily. Thanks.
