### ISSUE TITLE
Bypass guard given

### ISSUE THREAD

**Issue by eliasjtg** [sfelix-martins/passport-multiauth#34]
I used: auth:admin and test with user authenticated with guard user and this pass the authorization.

I find the issue in ... /vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php : 56

    if (empty($guards)) {
        return $this->auth->authenticate();
    }

This line return the authenticated user bypassing guard validation.

In ... /vendor/smartins/passport-multiauth/src/Http/Middleware/MultiAuthenticate.php : 59

    // If don't has any guard follow the flow
    if (empty($guards)) {
        return $next($request);
    }

If don't pass guard this follow the flow, else this must validate this guards...

I fix it overwritting authenticate method:

    /**
     * Determine if the user is logged in to any of the given guards.
     *
     * @param  array  $guards
     * @return void
     *
     * @throws \Illuminate\Auth\AuthenticationException
     */
    protected function authenticate(array $guards)
    {
        foreach ($guards as $guard) {
            if ($this->auth->guard($guard)->check()) {
                return $this->auth->shouldUse($guard);
            }
        }

        throw new AuthenticationException('Unauthenticated.', $guards);
    }

I am doing something wrong?

**Comment by sfelix-martins** [comment]
@eliasjtg Firstly, thanks for contribute.

Really the following code is wrong: 

```php
// If don't has any guard follow the flow
if (empty($guards)) {
    return $next($request);
}
```

I confess this worked for version 1.0, when the code that verified that the user was authenticated was called in a step afterwards. :disappointed: 

I think that it's not a very dangerous error, because when you try get the user instance, probably you will receive a `null` response. But it can cause a unexpected error.

For me, the best solution is just call the method `authenticate()` from parent class `Illuminate/Auth/Middleware/Authenticate` and on your core, the following code will be called, validating the error described above (`null` getting user).

```php
namespace Illuminate\Auth;

trait GuardHelpers
{
// ...
/**
     * Determine if the current user is authenticated.
     *
     * @return \Illuminate\Contracts\Auth\Authenticatable
     *
     * @throws \Illuminate\Auth\AuthenticationException
     */
    public function authenticate()
    {
        if (! is_null($user = $this->user())) {
            return $user;
        }

        throw new AuthenticationException;
    }

// ...
```

Finally, our code should looks like this:

In ... /vendor/smartins/passport-multiauth/src/Http/Middleware/MultiAuthenticate.php : 59
```php
// If don't has any guard follow the flow
if (empty($guards)) {
    return $this->authenticate($guards);
}
```

I created a PR #35  with the solution explained here. What do you think?

**Comment by fjobeir** [comment]
Since I have 'api' in all API guards, instead of checking `empty($guards)` I had to check whether the `$guards[0]` has 'api'
```
if ($guards && count($guards)) {
    if (strpos('api', $guards[0]) === false) {
        $this->authenticate($request, $guards);
        // Stop laravel from checking for a token if session is not set
        return $next($request);
    }
}
```
