### ISSUE TITLE
Unable to determine authentication model from configuration.

### ISSUE THREAD

**Issue by ayman1-elmalah** [sfelix-martins/passport-multiauth#37]
Issue when using admin auth
![5646757474](https://user-images.githubusercontent.com/37438338/43226509-5d226e22-905c-11e8-906e-d578d259fe8d.PNG)

**Comment by sfelix-martins** [comment]
Thanks for issue. Please send your `config/auth.php` and routes.

**Comment by skmdevmaster** [comment]
também estou com ete problema...O que pode ser?

**Comment by sfelix-martins** [comment]
@skmdevmaster Creio que possa ser algo na configuração. Por favor me envie seu `config/auth.php` e Arquivos de Rota

**Comment by CleverMatias** [comment]
Hello guys, take a look on Listeners, if you're working with, in the particular case of skmdev above it was the problem, < caused by me trying to get a guard before it even exists >.
portuguese: no caso da skmdev acima foi causado por mim em um listener tentando referenciar um guard que ainda não existia.

**Comment by sfelix-martins** [comment]
Good. Thanks for your feedback.
